baseURL = 'https://jmooring.github.io/hugo-sites/'
languageCode = 'en-us'
title = 'Hugo Sites'
disableKinds = ['RSS', 'sitemap']

[params]
show_all = false # If false, sites without generator tag will not be shown.

[taxonomies]
type = 'types'
visibility = 'visibility'

[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = -1

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = '10'

[[menu.main]]
name = 'Types'
pageRef = '/types'
weight = '20'

[[menu.main]]
name = 'Visibility'
pageRef = '/visibility'
weight = '30'
