baseURL = 'https://jmooring.github.io/hugo-sites/'
languageCode = 'en-us'
title = 'Hugo Sites'
disableKinds = ['RSS', 'sitemap']

[params]
show_all = false # If false, sites without generator tag will not be shown.

[taxonomies]
tag = 'tags'

[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = -1
