baseURL = 'https://jmooring.github.io/hugo-sites/'
languageCode = 'en-us'
title = 'Hugo Sites'
disableKinds = ['RSS', 'sitemap']
timeout = '60s'

[params]
show_all = false # If false, sites without generator tag will not be shown.
user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'

[taxonomies]
type = 'types'
visibility = 'visibility'

[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = '672h'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = '10'

[[menu.main]]
name = 'Types'
pageRef = '/types'
weight = '20'

[[menu.main]]
name = 'Visibility'
pageRef = '/visibility'
weight = '30'

[[menu.main]]
name = 'All'
pageRef = '/sites'
weight = '40'
